### ISSUE TITLE
After a user (not admin) is expired, wp_usermeta data 'uae_user_access_expired' = true, not cleared by updating user profile

### ISSUE THREAD

**Issue by zorgalina** [NateJacobs/User-Access-Expiration#4]
After a user is 'expired' the admin should be able to re-activate their account; sorry, but I didn't see a way to do this (aside from directly updating the row in the table).
thanks

**Comment by NateJacobs** [comment]
Under the User Access Expiration section of the user's profile page you should be able to select if the user has access to the site. On my test site I toggled the setting from Yes to No and the usermeta of ```uae_user_access_expired``` changed from FALSE (access allowed) to TRUE (access denied).

![screen shot 2015-03-03 at 17 36 12](https://cloud.githubusercontent.com/assets/827478/6475841/39c67af2-c1cc-11e4-87d3-eda38b4362d8.png)

If the meta is set to true, then the person does not have access.

**Comment by NateJacobs** [comment]
No further comments after 10 days. This issue will be closed as there is no indication it is a bug, but rather a support request.
